INSERT INTO `peliculas` (`id`, `titulo`, `duracion`, `genero`, `sinopsis`, `cartel`, `trailer`, `fechaEstreno`, `sesion_id`) VALUES
(1, 'La monja', 96, 'Terror/Misterio', 'Cuando una joven monja se quita la vida en un aislado monasterio de clausura en Rumanía, el Padre Burke (Demián Bichir).', './monja.jpg', 'https://www.youtube.com/watch?v=eqVjGwYFVqQ', '2024-09-07 00:00:00', NULL),
(2, 'Ant-Man i la Avispa: Quantumania', 125, 'Acción/Aventura', 'Scott Lang (Paul Rudd) está disfrutando de su vida como Vengador y de la fama que ha ganado por ayudar a salvar a la humanidad en Vengadores: Endgame. ', './ant.jpg', 'https://www.youtube.com/watch?v=ZlNFpri-Y40', '2024-04-17 00:00:00', NULL),
(3, 'Night Swim', 98, 'Terror/Misterio', 'Es historia de Ray Waller , una estrella del béisbol obligada a retirarse antes de tiempo debido a una enfermedad que le impide jugar.', './swim.jpg', 'https://www.youtube.com/watch?v=pcSNqteCEtE', '2024-03-09 00:00:00', NULL),
(4, 'Annabelle', 99, 'Terror/Misterio', 'Una pareja comienza a sufrir experiencias terroríficamente supernaturales en su hogar debido a una muñeca vintage.', './anna.jpg', 'https://www.youtube.com/watch?v=8kmLHwKH31M', '2024-10-08 00:00:00', NULL),
(5, 'Guardianes de la Galaxia vol. 3', 149, 'Acción/Aventura', 'Puede que Thanos , así como el padre de Peter Quill , Ego, sean ya historia, pero la horrible huella que han dejado tras de sí aún se palpa en el seno de los Guardianes de la Galaxia. ', '.guardianes.jpg', 'https://www.youtube.com/watch?v=F60FZKt_36s', '2024-05-05 00:00:00', NULL),
(6, 'Torrente, el brazo tonto de la ley', 97, 'Comedia/Acción', 'José Luis Torrente es un incompetente policía madrileño al que el destino va a dar la oportunidad de redimirse.', './torrente.jpg', 'https://www.youtube.com/watch?v=ulJSg4GYbBE', '2024-04-13 00:00:00', NULL),
(7, 'Resacon en las Vegas', 100, 'Comedia/Misterio', 'Después de una noche de excesos, los chicos comienzan el día sin recordar nada de lo que hicieron la noche anterior', './resaca.jpg', 'https://www.youtube.com/watch?v=MckEHmSMg-0', '2024-08-14 00:00:00', NULL),
(8, 'Avengers: Infinity War', 149, 'Acción/Ciencia ficción', 'Un nuevo peligro acecha procedente de las sombras del cosmos. Thanos, el infame tirano intergaláctico, tiene como objetivo reunir las seis Gemas del Infinito.', './infinty.jpg', 'https://www.youtube.com/watch?v=6ZfuNTqbHE8', '2024-04-27 00:00:00', NULL),
(9, 'Jurassic World', 124, 'Acción/Ciencia ficción', ' Isla Nubla tiene ahora un parque temático de dinosaurios en pleno funcionamiento llamado Jurassic World, como lo había previsto John Hammond.', './jurasic.jpg', 'https://www.youtube.com/watch?v=hv9eSCijf6E', '2024-06-10 00:00:00', NULL);
INSERT INTO novedades (id, title, sinopsis, estreno, poster, trailer) VALUES
(1, 'Teen Wolf La Pelicula', 'Scott Howard juega al baloncesto. No es ni el mejor jugador ni el más alto, pero no por ello desiste de su sueño: triunfar con el equipo del instituto.', '2024-03-26', 'wolf.jpg', 'https://www.youtube.com/watch?v=e2z8zO7rLSg'),
(2, 'Sinister', 'Ellison, es un periodista especializado en escribir artículos y novelas sobre casos de crímenes célebres.', '2024-10-31', 'sinister.jpg', 'https://www.youtube.com/watch?v=_kbQAJR9YWQ'),
(3, 'The Flash', 'Los mundos chocan en "Flash" cuando Barry utiliza sus superpoderes para viajar en el tiempo y cambiar los acontecimientos del pasado.', '2024-06-16', 'flash.jpg', 'https://www.youtube.com/watch?v=hebWYacbdvc'),
(4, 'Indiginous', 'inco amigos se encuentran en Panamá para una vacaciones. En una fiesta escuchan las historias acerca de una bonita cascada en el interior de la selva y, sin hacer caso a las advertencias, deciden ir a buscarla.', '2024-04-20', 'indiginous.jpg', 'https://www.youtube.com/watch?v=vDm-hItTkIE'),
(5, 'Inazuma Eleven La Pelicula', 'El colegio Raimon ha llegado a las semifinales de Fútbol Frontier y deben enfrentarse al Equipo Ogro del colegio Rey Colmillo. En la lucha se darán cuenta que las técnicas habituales no tendrán el mismo resultado, además de que la táctica empleada por el equipo contrincante no es común.', '2024-12-23', 'inazuma.jpg', 'https://www.youtube.com/watch?v=XpqXe3GAjrQ'),
(6, 'Five Nights at Freddy s', 'n hombre comienza un trabajo como guardia de seguridad nocturno en el restaurante Freddy Fazbear s Pizza, donde descubre que los animatrónicos se mueven por la noche y matan a cualquiera que vean. ', '2024-10-27', 'five.jpg', 'https://www.youtube.com/watch?v=0VH9WCFV6XQ'),
(7, 'Capitan America Civil War', 'Después de que otro incidente internacional involucre a Los Vengadores, causando varios daños colaterales, aumentan las presiones políticas para instaurar un sistema que exija más responsabilidades y que determine cuándo deben contratar los servicios del grupo de superhéroes.', '2024-04-29', 'capi.jpg', 'https://www.youtube.com/watch?v=dKrVegVI0Us'),
(8, 'Imaginary', 'Cuando Jessica vuelve con su familia a la casa de su infancia, Alice, su hijastra más pequeña, comienza a desarrollar un extraño apego hacia Chauncey, el oso de peluche que encuentra en el sótano.', '2024-03-15', 'imaginary.jpg', 'https://www.youtube.com/watch?v=8XoNfrgrAGM'),
(9, 'Escape Room', 'Seis personas quedan atrapadas en un escape room cuyo creador ha diseñado una trampa mortal en cada habitación. No saben por qué les está haciendo esto, pero sí saben que un solo error les costará la vida.', '2024-04-04', 'escape.jpg', 'https://www.youtube.com/watch?v=T5z2EwJTr9I'),
(10, 'Horror Park', 'El Padrino V es una película de 2024 dirigida por Francis Ford Coppola, secuela de El Padrino IV. La película cuenta la historia de la familia Corleone, con Vito Corleone a la cabeza, y su hijo Michael Corleone.', '2024-05-23', 'horror.jpg', 'https://www.youtube.com/watch?v=dqxSrZDTDgo'),
(11, 'Insidious', 'Josh (Patrick Wilson), su esposa Renai (Rose Byrne) y sus tres hijos acaban de mudarse a una vieja casa. Pero, tras un desgraciado accidente, uno de los niños entra en coma y, al mismo tiempo, empiezan a producirse en la casa extraños fenómenos que aterrorizan a la familia.', '2024-06-10', 'insidious.jpg', 'https://www.youtube.com/watch?v=FRW3K0LlsD0'),
(12, 'Verdad o Reto', 'Una inofensiva partida de Verdad o reto entre un grupo de amigos acaba convirtiéndose en un juego letal cuando alguien -o algo- empieza a castigar a los que mienten o no aceptan el reto.', '2024-04-13', 'reto.jpg', 'https://www.youtube.com/watch?v=YhSPDqqgO3Y');
